//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StitchOfflineMapCSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StitchOfflineMapCSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _6570_1265 {
            get {
                object obj = ResourceManager.GetObject("6570_1265", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6570_1266 {
            get {
                object obj = ResourceManager.GetObject("6570_1266", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6570_1267 {
            get {
                object obj = ResourceManager.GetObject("6570_1267", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6570_1268 {
            get {
                object obj = ResourceManager.GetObject("6570_1268", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6570_1269 {
            get {
                object obj = ResourceManager.GetObject("6570_1269", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6570_1270 {
            get {
                object obj = ResourceManager.GetObject("6570_1270", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6571_1265 {
            get {
                object obj = ResourceManager.GetObject("6571_1265", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6571_1266 {
            get {
                object obj = ResourceManager.GetObject("6571_1266", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6571_1267 {
            get {
                object obj = ResourceManager.GetObject("6571_1267", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6571_1268 {
            get {
                object obj = ResourceManager.GetObject("6571_1268", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6571_1269 {
            get {
                object obj = ResourceManager.GetObject("6571_1269", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6571_1270 {
            get {
                object obj = ResourceManager.GetObject("6571_1270", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6572_1265 {
            get {
                object obj = ResourceManager.GetObject("6572_1265", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6572_1266 {
            get {
                object obj = ResourceManager.GetObject("6572_1266", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6572_1267 {
            get {
                object obj = ResourceManager.GetObject("6572_1267", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6572_1268 {
            get {
                object obj = ResourceManager.GetObject("6572_1268", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6572_1269 {
            get {
                object obj = ResourceManager.GetObject("6572_1269", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6572_1270 {
            get {
                object obj = ResourceManager.GetObject("6572_1270", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6573_1265 {
            get {
                object obj = ResourceManager.GetObject("6573_1265", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6573_1266 {
            get {
                object obj = ResourceManager.GetObject("6573_1266", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6573_1267 {
            get {
                object obj = ResourceManager.GetObject("6573_1267", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6573_1268 {
            get {
                object obj = ResourceManager.GetObject("6573_1268", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6573_1269 {
            get {
                object obj = ResourceManager.GetObject("6573_1269", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6573_1270 {
            get {
                object obj = ResourceManager.GetObject("6573_1270", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6574_1265 {
            get {
                object obj = ResourceManager.GetObject("6574_1265", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6574_1266 {
            get {
                object obj = ResourceManager.GetObject("6574_1266", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6574_1267 {
            get {
                object obj = ResourceManager.GetObject("6574_1267", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6574_1268 {
            get {
                object obj = ResourceManager.GetObject("6574_1268", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6574_1269 {
            get {
                object obj = ResourceManager.GetObject("6574_1269", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6574_1270 {
            get {
                object obj = ResourceManager.GetObject("6574_1270", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6575_1265 {
            get {
                object obj = ResourceManager.GetObject("6575_1265", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6575_1266 {
            get {
                object obj = ResourceManager.GetObject("6575_1266", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6575_1267 {
            get {
                object obj = ResourceManager.GetObject("6575_1267", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6575_1268 {
            get {
                object obj = ResourceManager.GetObject("6575_1268", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6575_1269 {
            get {
                object obj = ResourceManager.GetObject("6575_1269", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6575_1270 {
            get {
                object obj = ResourceManager.GetObject("6575_1270", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6576_1265 {
            get {
                object obj = ResourceManager.GetObject("6576_1265", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6576_1266 {
            get {
                object obj = ResourceManager.GetObject("6576_1266", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6576_1267 {
            get {
                object obj = ResourceManager.GetObject("6576_1267", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6576_1268 {
            get {
                object obj = ResourceManager.GetObject("6576_1268", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6576_1269 {
            get {
                object obj = ResourceManager.GetObject("6576_1269", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6576_1270 {
            get {
                object obj = ResourceManager.GetObject("6576_1270", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6577_1265 {
            get {
                object obj = ResourceManager.GetObject("6577_1265", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6577_1266 {
            get {
                object obj = ResourceManager.GetObject("6577_1266", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6577_1267 {
            get {
                object obj = ResourceManager.GetObject("6577_1267", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6577_1268 {
            get {
                object obj = ResourceManager.GetObject("6577_1268", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6577_1269 {
            get {
                object obj = ResourceManager.GetObject("6577_1269", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6577_1270 {
            get {
                object obj = ResourceManager.GetObject("6577_1270", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6578_1265 {
            get {
                object obj = ResourceManager.GetObject("6578_1265", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6578_1266 {
            get {
                object obj = ResourceManager.GetObject("6578_1266", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6578_1267 {
            get {
                object obj = ResourceManager.GetObject("6578_1267", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6578_1268 {
            get {
                object obj = ResourceManager.GetObject("6578_1268", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6578_1269 {
            get {
                object obj = ResourceManager.GetObject("6578_1269", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6578_1270 {
            get {
                object obj = ResourceManager.GetObject("6578_1270", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
